services:
  db:
    image: postgres:15
    container_name: crypto_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data
    
  ingestion:
    build: ./data_ingestion 
    container_name: crypto_ingestion
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
    volumes:
      - ./data_ingestion:/app
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    volumes:
      - ./metabase_data:/metabase.db
    environment:
      - MB_DB_TYPE=h2
      - MB_DB_FILE=/metabase.db
    restart: always